{"inherits": "gold",
 "main": 
 { "size": [554, 484],
   "background-image": "$path/gbbg.png",
   "close": { "image": "$path/x.png",
              "loc": [539, 47]},
   "minimize": { "image": "$path/m.png",
                 "loc": [519, 50]},
   "menu" : { "loc": [214,44] },
   "chums": { "style": "border:0px; background-image:url($path/chumbg.png); background-color: rgb(110,110,110); background-repeat: no-repeat; color: white; font-family: 'Arial';selection-background-color:#646464; font-size:16px; ",
			  "loc": [207, 153],
              "size": [311, 105] },
   "mychumhandle": { "handle": { "style": "background: rgba(255, 255, 0, 0%); color:white; font-family:'Arial'; font-size:20px; text-align:left;",
                                 "loc": [245,290],
                                 "size": [263, 38] },
                     "currentMood": [217, 300] },
  "addchum":  { "style": "background: rgba(255, 255, 0, 0%); border:0px; color: rgba(0, 0, 0, 0%);",
              "loc": [40,0],
              "size": [118, 117],
                "text": ""
              },
  "pester": { "style": "background:  rgba(255, 255, 0, 0%); border:0px; font: bold; color:  rgba(255, 255, 0, 0%); font-family:'Arial';",
              "pressed" : "background-image:url($path/pesterdown.png);",
                "loc": [23,140],
                "size": [157, 124],
              "text": ""
            },
  "moodlabel": { "style": "",
				 "loc": [0,0],
				 "text": ""
			   },
  "moods": [
      { "style": "border:0px;", 
		"selected": "background:url($path/moodcheck1.png); border:0px;",
		"loc": [19, 342],
		"size": [168, 43],
	   	 "text": "",
		"icon": "",
		"mood": 0
	  },
      { "style": "border:0px;", 
		"selected": "background:url($path/moodcheck2.png); border:0px;",
		"loc": [19, 387],
		"size": [168, 43],
	   	 "text": "",
		"icon": "",
		"mood": 19
	  },
      { "style": "border:0px;", 
		"selected": "background:url($path/moodcheck3.png); border:0px;",
		"loc": [19, 432],
		"size": [168, 43],
	   	 "text": "",
		"icon": "",
		"mood": 20
	  },
      { "style": "border:0px;", 
		"selected": "background:url($path/moodcheck4.png); border:0px;",
		"loc": [192, 342],
		"size": [168, 43],
	   	 "text": "",
		"icon": "",
		"mood": 21
	  },
      { "style": "border:0px;", 
		"selected": "background:url($path/moodcheck5.png); border:0px;",
		"loc": [192, 387],
		"size": [168, 43],
	   	 "text": "",
		"icon": "",
		"mood": 22
	  },
      { "style": "border:0px;", 
		"selected": "background:url($path/moodcheck6.png); border:0px;",
		"loc": [192, 432],
		"size": [168, 43],
	   	 "text": "",
		"icon": "",
		"mood": 5
	  },
      { "style": "border:0px;", 
		"selected": "background:url($path/moodcheck7.png); border:0px;",
		"loc": [362, 342],
		"size": [168, 43],
	   	 "text": "",
		"icon": "",
		"mood": 6
	  },
      { "style": "border:0px;", 
		"selected": "background:url($path/moodcheck8.png); border:0px;",
		"loc": [362, 387],
		"size": [168, 43],
	   	 "text": "",
		"icon": "",
		"mood": 3
	  },
      { "style": "border:0px;", 
		"selected": "background:url($path/moodcheck9.png); border:0px;",
		"loc": [362, 432],
		"size": [168, 43],
	   	 "text": "",
		"icon": "",
		"mood": 1
	  },
      { "style": "border:0px;", 
		"selected": "border:0px;",
		"loc": [35, 300],
		"size": [140, 18],
	   	"text": "",
		"icon": "",
		"mood": 2
	  }
  ]
 }
}
