{"inherits": "trollian",
 "main": {
   "moods": [
      { "style": "border:0px;",
        "selected": "background-image:url($path/moodcheck1.png); border:0px;",
        "loc": [25, 141],
        "size": [20, 270],
        "text": "",
        "icon": "",
        "mood": 17
      },
      { "style": "border:0px;",
        "selected": "background-image:url($path/moodcheck2.png); border:0px;",
        "loc": [60, 141],
        "size": [20, 270],
        "text": "",
        "icon": "",
        "mood": 9
      },
      { "style": "border:0px;",
        "selected": "background-image:url($path/moodcheck3.png); border:0px;",
        "loc": [95, 141],
        "size": [20, 270],
        "text": "",
        "icon": "",
        "mood": 11
      },
      { "style": "border:0px;",
        "selected": "background-image:url($path/moodcheck4.png); border:0px;",
        "loc": [130, 141],
        "size": [20, 270],
        "text": "",
        "icon": "",
        "mood": 1
      },
      { "style": "border:0px;",
        "selected": "background-image:url($path/moodcheck5.png); border:0px;",
        "loc": [165, 141],
        "size": [20, 270],
        "text": "",
        "icon": "",
        "mood": 16
      },
      { "style": "border:0px;",
        "selected": "background-image:url($path/moodcheck6.png); border:0px;",
        "loc": [200, 141],
        "size": [20, 270],
        "text": "",
        "icon": "",
        "mood": 8
      },
      { "style": "border:0px;",
        "selected": "background-image:url($path/moodcheck7.png); border:0px;",
        "loc": [235, 141],
        "size": [20, 270],
        "text": "",
        "icon": "",
        "mood": 10
      },
      { "style": "border:0px;",
        "selected": "background-image:url($path/moodcheck8.png); border:0px;",
        "loc": [270, 141],
        "size": [20, 270],
        "text": "",
        "icon": "",
        "mood": 14
      },
      { "style": "border:0px;",
        "selected": "background-image:url($path/moodcheck9.png); border:0px;",
        "loc": [305, 141],
        "size": [20, 270],
        "text": "",
        "icon": "",
        "mood": 15
      },
      { "style": "border:0px;",
        "selected": "background-image:url($path/moodcheck10.png); border:0px;",
        "loc": [340, 141],
        "size": [20, 270],
        "text": "",
        "icon": "",
        "mood": 13
      },
      { "style": "border:0px;",
        "selected": "background-image:url($path/moodcheck11.png); border:0px;",
        "loc": [375, 141],
        "size": [20, 270],
        "text": "",
        "icon": "",
        "mood": 12
      },
      { "style": "border:0px;",
        "selected": "background-image:url($path/moodcheck12.png); border:0px;",
        "loc": [410, 141],
        "size": [20, 270],
        "text": "",
        "icon": "",
        "mood": 7
      },
      
      { "style": "border:0px;color: rgba(0, 0, 0, 0%);",
        "selected": "border:0px; color: rgba(0, 0, 0, 0%);",
        "loc": [12, 117],
        "size": [435, 18],
        "text": "",
        "icon": "",
        "mood": 2
      }
  ]
 }
}